version: "3"
services:
  web:
    build: .
    restart: always
    ports:
      - "808:808"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "5555:3306"
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: family_tree
